services:
  client:
    image: gonzalobertomeu/lacampana-dev
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - 4000:3000
    command: sh -c "pnpm install && pnpm dev"
  engine:
    image: gonzalobertomeu/lacampana-dev
    working_dir: /usr/src/app
    volumes:
      - ./engine:/usr/src/app
    ports:
      - 3000:3000
    command: sh -c "pnpm install && pnpm dev"
