services:
  client:
    image: gonzalobertomeu/bun-runtime-dev
    platform: linux/amd64
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - 4321:4321
    command: sh -c "bun install && bun dev --host"
  engine:
    image: gonzalobertomeu/bun-runtime-dev
    working_dir: /usr/src/app
    platform: linux/amd64
    volumes:
      - ./engine:/usr/src/app
    ports:
      - 1234:1234
    command: sh -c "bun install && bun dev"
